#!/usr/bin/sh

#
# insert following line at the top of Makefile.am
#
#   LOG_DRIVER := $(SHELL) test_wrapper $(top_srcdir)/config/test-driver
#
# or
#
#   $ make check LOG_DRIVER="test_wrapper /usr/share/automake-1.16/test-driver"
#

cmd="$@"

test_name=""

while [ "$#" -ne 0 ] ; do
  case $1 in
    --test-name )
      shift
      test_name="$1"
      ;;
    --trs-file )
      shift
      trs_file="$1"
      ;;
    -- )
      break
      ;;
    * )
      ;;
  esac

  shift
done

/usr/bin/time -o ${test_name}.time -p $cmd

echo ":test-name: ${test_name}" >> ${trs_file}
cat ${test_name}.time | awk '{ print ":" $1 "-time: " $2 }' >> ${trs_file}

